Name:           ros-melodic-fmi-adapter
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS fmi_adapter package

Group:          Development/Libraries
License:        Apache License 2.0
URL:            http://wiki.ros.org/fmi_adapter
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-roscpp
Requires:       ros-melodic-std-msgs
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-std-msgs

%description
Wraps FMUs for co-simulation

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Oct 12 2018 Ralph Lange <ralph.lange@de.bosch.com> - 1.0.2-0
- Autogenerated by Bloom

* Mon Jul 16 2018 Ralph Lange <ralph.lange@de.bosch.com> - 1.0.1-0
- Autogenerated by Bloom

* Fri Jul 13 2018 Ralph Lange <ralph.lange@de.bosch.com> - 1.0.0-0
- Autogenerated by Bloom

