name: "Build action: Noetic"

on:
  push:
    branches: [ noetic ]
  pull_request:
    branches: [ noetic ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [ noetic ]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@0.0.26
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@0.1.0
      with:
        package-name: fmi_adapter
        vcs-repo-file-url: ""
        target-ros1-distro: ${{ matrix.ros_distribution }}
